on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Create Properties
        uses: actions/checkout@v3
      - run: touch ./src/main/resources/application-awsMariaDB.properties
      - run: echo "${{ secrets.APPLICATION_AWSMARIADB_PROPERTIES }}" > ./src/main/resources/application-awsMariaDB.properties
      - run: cat ./src/main/resources/application-awsMariaDB.properties

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build with Gradle
        run: |
          ./gradlew build

      - name: ssh connection
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          pass: ${{ secrets.PW }}
          first_ssh: |
            cd /home/${{ secrets.USER }}/server/
            pkill -f LFG
            if [ -e LFG* ]; then rm -f LFG*; fi
            if [ -f nohup.out ]; then mv nohup.out nohup_$(date +%Y%m%d).out; mv nohup_$(date +%Y%m%d).out /home/${{ secrets.USER }}/mylog/; fi
          scp: |
            ./build/libs/LFG*-SNAPSHOT.jar => /home/${{ secrets.USER }}/server/
          last_ssh: |
            cd /home/${{ secrets.USER }}/server/
            echo "${{ secrets.PW }}" | sudo -S nohup java -jar LFG* > /home/${{ secrets.USER }}/server/nohup.out 2>&1 &
